package com.claro.cobillingweb.persistence.dao.query;

public class DisponibilizacaoPacotePrePagoDAONativeSQL {

	public static final String SQL = "SELECT trunc(A.DT_INICIO_FRANQUIA) AS DATA_REFERENCIA, " +
			"	CLARO.DS_OPERADORA AS OPERADORA_CLARO, " +
			"	LD.DS_OPERADORA AS OPERADORA_LD, " +
			"	A.NU_TELEFONE AS TERMINAL, " +
			"	DOM.DS_DOMINIO AS STATUS_ASSINATURA,       " +
			"	P.NO_PACOTE_PREPAGO ||' '|| A.QT_MINUTOS_ADQUIRIDOS AS DESCRICAO_PACOTE,	" +
			"	A.CD_PRODUTO_PREPAGO AS PRODUTO,	" +
			"	SUM(A.QT_CDRS) AS QTD_CDRS, " +
			"	COUNT(A.NU_TELEFONE) AS QTD_PACOTES, " +
			"	SUM(A.HR_DURACAO_REAL) AS DURACAO_REAL, " +
			"	SUM(A.QT_MIN_TARIFADOS_FRANQUIA) AS QTD_CONSUMIDA, " +
			"	SUM(A.VL_BRUTO_PACOTE) AS VL_BRUTO " +
			" FROM   SCC_ASSINATURA_PREPAGO A, SCC_PACOTE_PREPAGO P, SCC_OPERADORA CLARO, SCC_OPERADORA LD,	" +
			"		SCC_PRE_DOMINIO DOM, SCC_CDR_COBL CC " +
			" WHERE  CLARO.CD_EOT = A.CD_EOT_CLARO " +
			"		AND LD.CD_EOT = A.CD_EOT_LD" +
			"		AND A.CD_STATUS_ASSINATURA = DOM.CD_DOMINIO" +
			"		AND DOM.TP_DOMINIO = 'STASS'" +
			"		AND A.CD_PACOTE_PREPAGO = P.CD_PACOTE_PREPAGO" +
			"		AND A.CD_PRODUTO_PREPAGO = CC.CD_PRODUTO_PREPAGO" +
			"		AND A.NU_TELEFONE = CC.NU_MSISDN_ORIGEM ";
									
	public static final String FILTRO_DATA_INICIAL = " AND A.DT_INICIO_FRANQUIA  >= :dataInicial ";
	public static final String FILTRO_DATA_FINAL = " AND A.DT_INICIO_FRANQUIA  <= :dataFinal ";
	public static final String FILTRO_PACOTE = " AND A.CD_PACOTE_PREPAGO = :cdPacote ";
	public static final String FILTRO_OPERADORA_CLARO = " AND CLARO.CD_EOT = :cdEOTClaro ";
	public static final String FILTRO_OPERADORA_EXTERNA = " AND LD.CD_EOT  = :cdEOTLD ";
	public static final String FILTRO_DATA_INICIAL_PROC_EXTERNA = " AND CC.DT_PROC_EXTERNA >= :dataInicialProcExterna ";
	public static final String FILTRO_DATA_FINAL_PROC_EXTERNA = " AND CC.DT_PROC_EXTERNA <= :dataFinalProcExterna ";
	
	public static final String PROJECTIONS = "GROUP BY trunc(A.DT_INICIO_FRANQUIA), " +
		" 	CLARO.DS_OPERADORA, " +
		"	LD.DS_OPERADORA, " +
		"	A.NU_TELEFONE, " +
		"	DOM.DS_DOMINIO," +
		"	P.NO_PACOTE_PREPAGO || ' ' || A.QT_MINUTOS_ADQUIRIDOS," +
		"	A.CD_PRODUTO_PREPAGO";
								
	public static final String SQL_TOTAL = "SELECT COUNT(NU_CDR) QTD_CDRS,	" +
			"		SUM(CC.HR_DURACAO_REAL) DURACAO_REAL, " +
			"		NVL((SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_1) + SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_2) +	" +
			"			SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_3) + SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_4) +" +
			"	    	SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_5) + SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_6) +" +
			"			SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_7) + SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_8) +" +
			"			SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_9) + SUM(CC.QT_MINUTOS_TARIF_FRANQUIA_10)),0) QTD_CONSUMIDA	" +
			"	FROM   SCC_CDR_COBL CC, SCC_ASSINATURA_PREPAGO A, SCC_OPERADORA CLARO, SCC_OPERADORA LD	" +
			"	WHERE  CLARO.CD_EOT = A.CD_EOT_CLARO " +
			"		AND LD.CD_EOT = A.CD_EOT_LD" +
			"		AND CC.NU_MSISDN_ORIGEM = A.NU_TELEFONE" +
			"		AND CC.CD_PRODUTO_PREPAGO = A.CD_PRODUTO_PREPAGO " +
			"		AND (CC.CD_DEFEITO IS NULL OR CC.CD_DEFEITO <> '260') ";
}
