package com.claro.cobillingweb.persistence.dao.query;

public class PesquisaCDRsPrePagoSQL {

	public static final String SQL = "SELECT F.CD_EOT_LD, "+
        " F.CD_EOT_CLARO , "+
			"  A.CD_EOT_ORIGEM AS CD_EOT_SG_UF, "+
			" A.DT_CHAMADA, "+
			" A.DT_PROC_EXTERNA, "+
			" A.DT_REPASSE, "+
			" SUBSTR(A.NU_TELEFONE_DESTINO,1,2) AS AS_CN_ASSINANTE_A, "+
			" A.CD_EOT_ORIGEM,  "+
			" A.CD_EOT_ORIGEM AS CD_EOT_DS_OPERADORA, "+
			" D.DS_DOMINIO AS CD_DEFEITO, "+
			" H.DS_DOMINIO AS CD_PERIODO_CHAMADA, "+
			" G.DS_DOMINIO AS CD_TIPO_CHAMADA,  "+
			" E.DS_DOMINIO AS CD_STATUS_REGISTRO   "+
			" FROM SCC_CDR_COBL A,  "+
			" SCC_STATUS_CDR_COBL C,  "+
			" (SELECT CD_DOMINIO, DS_DOMINIO, TP_DOMINIO FROM SCC_PRE_DOMINIO WHERE TP_DOMINIO = 'DEFCH') D, "+ 
			" (SELECT CD_DOMINIO, DS_DOMINIO, TP_DOMINIO FROM SCC_PRE_DOMINIO WHERE TP_DOMINIO = 'STCHM') E,  "+
			" SCC_ARQUIVO_COBILLING F,  "+
			" (SELECT CD_DOMINIO, DS_DOMINIO, TP_DOMINIO FROM SCC_PRE_DOMINIO WHERE TP_DOMINIO = 'TPCHM') G, "+         
			" (SELECT CD_DOMINIO, DS_DOMINIO, TP_DOMINIO FROM SCC_PRE_DOMINIO WHERE TP_DOMINIO = 'PRCHM') H     "+     
			" WHERE  "+
			" A.SQ_ARQUIVO_REMESSA = F.SQ_ARQUIVO "+ 
			"  AND F.CD_TIPO_ARQUIVO IN (200,205)  "+
			"  AND A.NU_CDR = C.NU_CDR  "+
			"  AND C.CD_DEFEITO = D.CD_DOMINIO(+) "+ 
			"  AND D.TP_DOMINIO = 'DEFCH'  "+
			"  AND TO_CHAR(C.CD_STATUS_CDR) = E.CD_DOMINIO(+) "+ 
			"  AND E.TP_DOMINIO = 'STCHM'  "+
			"  AND A.CD_TIPO_CHAMADA = G.CD_DOMINIO(+) "+ 
			"  AND G.TP_DOMINIO = 'TPCHM'  "+
			"  AND A.CD_PERIODO_CHAMADA = H.CD_DOMINIO(+) "+ 
			"  AND H.TP_DOMINIO = 'PRCHM'   ";
	
	public static final String FILTRO_DT_CHAMADA = " AND A.DT_CHAMADA BETWEEN :dtInicial AND :dtFinal";
	public static final String FILTRO_DT_APURACAO = " AND A.DT_PROC_EXTERNA BETWEEN :dtInicial AND :dtFinal";
	public static final String FILTRO_DT_FECHAMENTO =" AND A.DT_REPASSE BETWEEN :dtInicial AND :dtFinal";
	
	public static final String FILTRO_OPERADORA_LD = "  AND F.CD_EOT_LD = :cdEOTLD";
	public static final String FILTRO_OPERADORA_CLARO = "  AND F.CD_EOT_CLARO = :cdEOTClaro";
	public static final String FILTRO_HOLDING_CLARO = "  AND F.CD_EOT_CLARO IN ( SELECT O1.CD_EOT FROM SCC_OPERADORA O1, SCC_OPERADORA O2 WHERE O1.CD_EOT_HOLDING = O2.CD_EOT_HOLDING AND O2.CD_EOT = :cdEOTClaro AND O1.CD_TIPO_SERVICO = 'M' AND O2.CD_TIPO_SERVICO = 'M' )";
	
	
}
