-- MySQL Script generated by MySQL Workbench
-- Ter 02 Jun 2015 08:38:48 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema julius
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `julius` ;

-- -----------------------------------------------------
-- Schema julius
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `julius` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `julius` ;

-- -----------------------------------------------------
-- Table `julius`.`source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `julius`.`source` (
  `id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `active` INT NOT NULL,
  `url_query` VARCHAR(1000) NOT NULL,
  `days_to_purge` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `julius`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `julius`.`post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `html` VARCHAR(10000) NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `source_id` INT NOT NULL,
  `external_id` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promo_source_idx` (`source_id` ASC),
  UNIQUE INDEX `ck_post` (`external_id` ASC, `source_id` ASC),
  INDEX `source` (`source_id` ASC),
  CONSTRAINT `fk_promo_source`
    FOREIGN KEY (`source_id`)
    REFERENCES `julius`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `julius`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `julius`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `julius`.`words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `julius`.`words` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(200) NOT NULL,
  `relevance` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_words_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_words_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `julius`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `julius`.`post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `julius`.`post_category` (
  `post_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`post_id`, `category_id`),
  INDEX `fk_promo_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_promo_has_category_promo1_idx` (`post_id` ASC),
  CONSTRAINT `fk_promo_has_category_promo1`
    FOREIGN KEY (`post_id`)
    REFERENCES `julius`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promo_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `julius`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `julius`.`post_bkp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `julius`.`post_bkp` (
  `id` INT UNSIGNED NOT NULL,
  `html` VARCHAR(10000) NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `source_id` INT NOT NULL,
  `external_id` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ck_post` (`external_id` ASC, `source_id` ASC),
  INDEX `source` (`source_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `julius`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `julius`.`user` (
  `reg_id` VARCHAR(4000) NOT NULL,
  `platform` VARCHAR(45) NOT NULL,
  `registration_date` DATETIME NOT NULL,
  `active_notifications` INT NOT NULL DEFAULT 1,
  `active_vibration` INT NOT NULL DEFAULT 1,
  `active_filter` INT NOT NULL DEFAULT 0,
  `word1` VARCHAR(45) NULL,
  `word2` VARCHAR(45) NULL,
  `word3` VARCHAR(45) NULL,
  PRIMARY KEY (`reg_id`(200)),
  INDEX `platform` (`platform` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `julius`.`source`
-- -----------------------------------------------------
START TRANSACTION;
USE `julius`;
INSERT INTO `julius`.`source` (`id`, `name`, `active`, `url_query`, `days_to_purge`) VALUES (1, 'Gatry', 1, 'https://gatry.com/', 2);
INSERT INTO `julius`.`source` (`id`, `name`, `active`, `url_query`, `days_to_purge`) VALUES (2, 'Hardmob', 1, 'http://www.hardmob.com.br/archive/index.php/f-407.html', 2);
INSERT INTO `julius`.`source` (`id`, `name`, `active`, `url_query`, `days_to_purge`) VALUES (3, 'CDI', 1, 'https://www.facebook.com/originalcdi', 2);

COMMIT;