package com.claro.sccweb.service.helper;


/**
 * Constantes associando códigos de itens de repasse com descrições no demonstrativo.
 *
 */
public class DemonstrativoPosPagoConstantes {

	/**
	 * Constante para indicar que o item do demonstrativo é só um título.
	 */
	public static final Long TITULO = -1L;
	public static final Long TOTAL_DO_VALOR_ARRECADADO = 29L;
	public static final Long VALOR_ARRECADADO_CORRENTE = 30L; 
	public static final Long JUROS_MULTAS_CORRENTE = 31L;
	public static final Long VALOR_ARRECADADO_APOS_EXPURGO = 32L;
	public static final Long JUROS_MULTAS_APOS_90_DIAS = 33L;
	public static final Long VALOR_ARRECADADO_DE_PARCELAMENTOS = 34L;
	public static final Long TOTAL_DAS_DEDUCOES = 28L;
	public static final Long CONTESTACAO_APOS_REPASSE = 35L;	
	public static final Long REVERSOES_PAGAMENTO_APOS_REPASSE = 36L;
	public static final Long REMUNERACAO_SERVICO_CONTRATADO = 22L;
	public static final Long DETALHAMENTO_CHAMADAS_FATURADAS = 37L;
	public static final Long REMUNERACAO_SERVICO_EXTRA_CARTAO = 38L;
	public static final Long REMUNERACAO_SERVICO_EXTRA_COBRANCA = 39L;
	public static final Long ACERTO_CONCILIACAO_CONTRA_CLARO = 9L;
	public static final Long ACERTO_CONCILIACAO_CONTRA_OPERADORA_LD = 8L;
	public static final Long PENALIDADE_REJEICOES_INDEVIDAS_CONTRA_CLARO = 10L;
	public static final Long PENALIDADE_REJEICOES_DEVIDAS_CONTRA_LD = 11L;
	public static final Long PENALIDADE_CHAMADA_PERDIDA_CONTRA_CLARO = 42L;
	public static final Long PENALIDADE_SLA_CONTRA_CLARO = 43L;
	public static final Long MULTAS_JUROS_ATRASO_REPASSE_CONTRA_CLARO = 12L;
	public static final Long MULTAS_JUROS_ATRASO_PAGAMENTO_CONTRA_LD = 13L;
	public static final Long TOTAL_DOS_ACERTOS = -2L;
	public static final Long TOTAL_DAS_PENALIDADES = -3L;
	
	/**
	 * A ordem com que os itens são listados nesse array será a mesma ordem com que serão populados no demonstrativo.
	 */
	public static Long[] CONFIGURACAO_DEMONSTRATIVO_REPASSE_POS =  new Long[]{
			TOTAL_DO_VALOR_ARRECADADO,
			VALOR_ARRECADADO_CORRENTE, 
			JUROS_MULTAS_CORRENTE,
			VALOR_ARRECADADO_APOS_EXPURGO,
			JUROS_MULTAS_APOS_90_DIAS,
			VALOR_ARRECADADO_DE_PARCELAMENTOS,
			TOTAL_DAS_DEDUCOES,
			CONTESTACAO_APOS_REPASSE,	
			REVERSOES_PAGAMENTO_APOS_REPASSE,
			REMUNERACAO_SERVICO_CONTRATADO,			
			DETALHAMENTO_CHAMADAS_FATURADAS,
			REMUNERACAO_SERVICO_EXTRA_CARTAO,
			REMUNERACAO_SERVICO_EXTRA_COBRANCA,
			TOTAL_DOS_ACERTOS,
			ACERTO_CONCILIACAO_CONTRA_CLARO,
			ACERTO_CONCILIACAO_CONTRA_OPERADORA_LD,
			TOTAL_DAS_PENALIDADES,
			PENALIDADE_REJEICOES_INDEVIDAS_CONTRA_CLARO,
			PENALIDADE_REJEICOES_DEVIDAS_CONTRA_LD,
			PENALIDADE_CHAMADA_PERDIDA_CONTRA_CLARO,
			PENALIDADE_SLA_CONTRA_CLARO,
			MULTAS_JUROS_ATRASO_REPASSE_CONTRA_CLARO,
			MULTAS_JUROS_ATRASO_PAGAMENTO_CONTRA_LD};
	
	/**
	 * Tìtulos para os ítens configurados no array CONFIGURACAO_DEMONSTRATIVO_REPASSE_POS
	 */
	public static String[] TITULOS_DEMONSTRATIVO_REPASSE_POS = new String[]{
			"1 - TOTAL DO VALOR ARRECADADO",
			"1.1 VALOR ARRECADADO CORRENTE",
			"1.2 JUROS+MULTAS CORRENTE",
			"1.3 VALOR ARRECADADO APÓS EXPURGO",
			"1.4 JUROS+MULTAS APÓS 90 DIAS",
			"1.5 VALOR ARRECADADO DE PARCELAMENTOS",
			"2 - TOTAL DAS DEDUÇÕES",
			"    2.1 CONTESTAÇÕES DE CLIENTES APÓS REPASSE",
			"    2.2 REVERSÕES DE PAGAMENTO APÓS REPASSE",
			"    2.3 REMUNERAÇÃO DO SERVIÇOO OBJETO DO CONTRATO",
			"          2.3.1 DETALHAMENTO DAS CHAMADAS FATURADAS",
			"     2.4 REMUNERAÇÃO DO SERVIÇO EXTRA DE ADM. DE CARTÕES (OPCIONAL)",
			"     2.5 REMUNERAÇÃO DO SERVIÇO EXTRA DE COBRANÇA ESPECIAL (OPCIONAL)",			
			"3 - TOTAL DOS ACERTOS",
			"     3.1 ACERTO DE CONCILIAÇÃO CONTRA CLARO",
			"     3.2 ACERTO DE CONCILIAÇÃO CONTRA PRESTADORA LD",
			"4 - TOTAL DAS PENALIDADES",
			"     4.1 PENALIDADE POR REJEIÇÕES INDEVIDAS CONTRA CLARO",
			"     4.2 PENALIDADE POR REJEIÇÕES DEVIDAS CONTRA PRESTADORA LD",
			"     4.3 PENALIDADE POR CHAMADA PERDIDA CONTRA CLARO",
			"     4.4 PENALIDADE POR DESEMPENHO GERAL CONTRA CLARO (SLA)",
			"     4.5 MULTA/JUROS POR ATRASO NO REPASSE CONTRA CLARO",
			"     4.6 MULTA/JUROS POR ATRASO NO PAGAMENTO CONTRA PRESTADORA LD"};
	
	
	
}
