package com.claro.cobillingweb.persistence.dao.query;

public class ConsolidadoProdutoSQL {
	
	public static final String SQL_PRE = "SELECT /*+PARALLEL(CDR, 8)*/	" +
			"	COUNT(1) AS QT_CDRS," +
			"	CAST(CDR.CD_CSP AS VARCHAR2(3)),	" +
			"	CDR.CD_EOT_ORIGEM,	" +
			"	CDR.CD_PRODUTO_PREPAGO,	" +
			"	CDR.CD_TIPO_EVENTO," +
			"	CDR.DT_CHAMADA," +
			"	CDR.IN_CHAMADA_REPASSADA," +
			"	CDR.DT_REPASSE," +
			"	SUM(CDR.MI_DURACAO_TARIFADA) AS MI_DURACAO_TARIFADA," +
			"	SUM(CDR.VL_BRUTO_CHAMADA) AS VL_BRUTO_CHAMADA," +
			"	CDR.CD_PACOTE_PREPAGO_1," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_1) AS QT_MINUTOS_TARIF_FRANQUIA_1," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_1) AS VL_TARIFADO_FRANQUIA_1," +
			"	CDR.CD_PACOTE_PREPAGO_2," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_2) AS QT_MINUTOS_TARIF_FRANQUIA_2," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_2) AS VL_TARIFADO_FRANQUIA_2," +
			"	CDR.CD_PACOTE_PREPAGO_3," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_3) AS QT_MINUTOS_TARIF_FRANQUIA_3," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_3) AS VL_TARIFADO_FRANQUIA_3," +
			"	CDR.CD_PACOTE_PREPAGO_4," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_4) AS QT_MINUTOS_TARIF_FRANQUIA_4," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_4) AS VL_TARIFADO_FRANQUIA_4," +
			"	CDR.CD_PACOTE_PREPAGO_5," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_5) AS QT_MINUTOS_TARIF_FRANQUIA_5," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_5) AS VL_TARIFADO_FRANQUIA_5," +
			"	CDR.CD_PACOTE_PREPAGO_6," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_6) AS QT_MINUTOS_TARIF_FRANQUIA_6," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_6) AS VL_TARIFADO_FRANQUIA_6," +
			"	CDR.CD_PACOTE_PREPAGO_7," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_7) AS QT_MINUTOS_TARIF_FRANQUIA_7," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_7) AS VL_TARIFADO_FRANQUIA_7," +
			"	CDR.CD_PACOTE_PREPAGO_8," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_8) AS QT_MINUTOS_TARIF_FRANQUIA_8," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_8) AS VL_TARIFADO_FRANQUIA_8," +
			"	CDR.CD_PACOTE_PREPAGO_9," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_9) AS QT_MINUTOS_TARIF_FRANQUIA_9," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_9) AS VL_TARIFADO_FRANQUIA_9," +
			"	CDR.CD_PACOTE_PREPAGO_10," +
			"	SUM(CDR.QT_MINUTOS_TARIF_FRANQUIA_10) AS QT_MINUTOS_TARIF_FRANQUIA_10," +
			"	SUM(CDR.VL_TARIFADO_FRANQUIA_10) AS VL_TARIFADO_FRANQUIA_10  " +
			"FROM   SCC_CDR_COBL CDR, SCC_OPERADORA OP " +
			"WHERE OP.CD_CSP = OP.CD_CSP AND CDR.DT_PROC_EXTERNA <= TRUNC(SYSDATE - 1) AND   CDR.CD_STATUS_CDR = 200 ";
	
	
	public static final String CD_EOT_LD_PRE = " AND OP.CD_EOT = :cdEOTLd " ;
	public static final String CD_EOT_CLARO_PRE = " AND CDR.CD_EOT_ORIGEM = :cdEOTClaro ";
	public static final String DT_INICIAL_REPASSE = " AND CDR.DT_CHAMADA >= :dataInicial ";
	public static final String DT_FIM_REPASSE =" AND CDR.DT_CHAMADA < (:dataFinal)+1 ";
	public static final String CD_PRODUTO_PREPAGO = " AND CDR.cd_produto_prepago = :cdProdutoPrepago";

	public static final String PROJECTIONS = " GROUP BY CDR.CD_CSP,	" +
			"	CDR.CD_EOT_ORIGEM," +
			"	CDR.CD_PRODUTO_PREPAGO," +
			"	CDR.CD_TIPO_EVENTO," +
			"	CDR.DT_CHAMADA," +
			"	CDR.IN_CHAMADA_REPASSADA," +
			"	CDR.DT_REPASSE," +
			"	CDR.CD_PACOTE_PREPAGO_1," +
			"	CDR.CD_PACOTE_PREPAGO_2," +
			"	CDR.CD_PACOTE_PREPAGO_3," +
			"	CDR.CD_PACOTE_PREPAGO_4," +
			"	CDR.CD_PACOTE_PREPAGO_5," +
			"	CDR.CD_PACOTE_PREPAGO_6," +
			"	CDR.CD_PACOTE_PREPAGO_7," +
			"	CDR.CD_PACOTE_PREPAGO_8," +
			"	CDR.CD_PACOTE_PREPAGO_9," +
			"	CDR.CD_PACOTE_PREPAGO_10";     


}
